services:
  postgres:
    container_name: ${DB_HOST}
    build: 
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      
  golang:
    container_name: ${GO_HOST}
    hostname: ${GO_ADDRESS}
    tty: true
    build: 
      context: .
      dockerfile: ./docker/go/Dockerfile
    volumes:
      - ./src:/go/src/app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_HOST: ${DB_HOST} 
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
